export type DemoExportFormat = 'pdf' | 'docx' | 'csv' | 'txt' | 'png';

export type DemoExportSection = {
  heading: string;
  lines: Array<string | number | boolean | undefined | null>;
};

type DemoExportOptions = {
  filenameBase: string;
  title: string;
  sections: DemoExportSection[];
  csvRows?: Array<Record<string, string | number | boolean | undefined | null>>;
};

const mimeByFormat: Record<Exclude<DemoExportFormat, 'png'>, string> = {
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  csv: 'text/csv',
  txt: 'text/plain',
};

function cleanFilename(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 400);
}

function buildTextReport(options: DemoExportOptions) {
  const body = options.sections
    .map((section) => {
      const lines = section.lines.filter((line) => line !== undefined && line !== null && String(line).trim() !== '');
      return [`## ${section.heading}`, ...lines.map((line) => String(line))].join('\n');
    })
    .join('\n\n');

  return `${options.title}\nGenerated by DIFARYX demo\n${new Date().toLocaleString()}\n\n${body}\n`;
}

function buildCsv(options: DemoExportOptions) {
  const rows = options.csvRows ?? options.sections.flatMap((section) => section.lines.map((line) => ({
    section: section.heading,
    value: line ?? '',
  })));
  const headers = Array.from(new Set(rows.flatMap((row) => Object.keys(row))));
  const escapeCell = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`;
  return [headers.join(','), ...rows.map((row) => headers.map((header) => escapeCell(row[header])).join(','))].join('\n');
}

export function exportDemoArtifact(format: DemoExportFormat, options: DemoExportOptions) {
  const filenameBase = cleanFilename(options.filenameBase || options.title || 'difaryx-export');

  if (format === 'png') {
    exportDemoPng(filenameBase, options.title, options.sections);
    return;
  }

  const content = format === 'csv' ? buildCsv(options) : buildTextReport(options);
  const blob = new Blob([content], { type: mimeByFormat[format] });
  downloadBlob(blob, `${filenameBase}.${format}`);
}

export function exportDemoPng(filenameBase: string, title: string, sections: DemoExportSection[]) {
  const canvas = document.createElement('canvas');
  const width = 1200;
  const height = 760;
  canvas.width = width;
  canvas.height = height;
  const context = canvas.getContext('2d');

  if (!context) {
    const fallback = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="#f8fafc"/><text x="48" y="72" font-family="Arial" font-size="32" fill="#0f172a">${title}</text></svg>`;
    downloadBlob(new Blob([fallback], { type: 'image/svg+xml' }), `${cleanFilename(filenameBase)}.svg`);
    return;
  }

  context.fillStyle = '#f8fafc';
  context.fillRect(0, 0, width, height);
  context.fillStyle = '#ffffff';
  context.strokeStyle = '#cbd5e1';
  context.lineWidth = 2;
  context.roundRect(40, 36, width - 80, height - 72, 18);
  context.fill();
  context.stroke();

  context.fillStyle = '#1d4ed8';
  context.font = '700 24px Arial';
  context.fillText('DIFARYX', 72, 86);
  context.fillStyle = '#0f172a';
  context.font = '700 34px Arial';
  context.fillText(title, 72, 132);

  let y = 184;
  sections.slice(0, 5).forEach((section) => {
    context.fillStyle = '#0f172a';
    context.font = '700 20px Arial';
    context.fillText(section.heading, 72, y);
    y += 30;
    context.fillStyle = '#475569';
    context.font = '16px Arial';
    section.lines.slice(0, 4).forEach((line) => {
      context.fillText(String(line ?? '').slice(0, 110), 92, y);
      y += 24;
    });
    y += 20;
  });

  canvas.toBlob((blob) => {
    if (blob) downloadBlob(blob, `${cleanFilename(filenameBase)}.png`);
  }, 'image/png');
}
